In [1]:
import sympy as sym
sym.init_printing()
from IPython.display import display , Math
import numpy as np

In [2]:
A = [[1,2],[3,4]]
A

In [3]:
type(A)

list

In [4]:
A = np.array([[1,2],[3,4]])
type(A)

numpy.ndarray

In [5]:
A

array([[1, 2],
       [3, 4]])

In [6]:
display(Math(sym.latex(sym.simplify(A))))

<IPython.core.display.Math object>

In [8]:
math = np.zeros([4,6])

In [9]:
display(Math(sym.latex(sym.simplify(math))))

<IPython.core.display.Math object>

In [12]:
math[0,1] = 2
math[2,4] = 7
display(Math(sym.latex(sym.simplify(math))))

<IPython.core.display.Math object>

In [16]:
numberRange = range(0,4)
math = np.zeros([4,6])
math[0,1] = 2
math[2,4] = 7
for rowi in numberRange:
    for coli in numberRange:
        math[rowi, coli] = (-1)**(rowi+coli)

math
        

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [17]:
x,y = sym.symbols('x,y')
Fxy = (4+x) * (2-y)
xyset = range(0,3)

outmat = np.zeros([len(xyset), len(xyset)])
outmat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i, y:j})
outmat

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])

In [19]:
display(Math(sym.latex(sym.simplify(outmat))))

<IPython.core.display.Math object>