In [1]:
import numpy as np

In [3]:
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them




# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(Ds)
#A+B
A+C

[[-2.35531818 -0.6351729   1.52532033 -0.87428859  0.42749738]
 [ 0.78248647  1.04584728 -1.22703015 -1.70413873  0.65239801]
 [-1.13680957  1.26723052  0.63550733  1.54911218  0.17316052]
 [ 0.16687967  1.74642004 -0.24575398  1.06541849 -1.91719439]
 [-1.48599941 -1.26193588  0.70892843 -0.50234551 -0.64910058]]


array([[-2.81516301e-01,  5.93929470e-01, -1.21199655e+00,
         1.00503168e+00],
       [ 7.76435673e-01, -1.17568080e+00,  2.45332057e+00,
         2.57717235e-01],
       [ 2.51460553e+00, -7.26138391e-01,  2.76102150e+00,
         1.88534232e+00],
       [-3.78214667e-01,  4.41714975e-05, -6.54054431e-01,
         6.85962798e-01],
       [ 1.47470475e+00, -1.08809403e+00,  1.85199255e+00,
         1.30395595e+00]])